### ISSUE TITLE
updateComponents.sh should probably limit git clone depth

### ISSUE THREAD

**Issue by barawn** [anitaNeutrino/anitaBuildTool#3]
Right now anitaBuildTool makes a full clone (just "git clone $repName"), which can take a lot more space than is needed if the component in question has a lot of history (like icemc, due to the roughness tables being added/removed). Because 'trunk' is used to build for all of those components anyway, it doesn't really make a lot of sense to make a full copy, so you can save a bit of space (and download time) by just changing

git clone $repName

to

git clone --depth 1 $repName

For the masochists who later want the full histories, it's easy enough to go to the directory and backfill it using git pull --unshallow or git fetch --depth=X (for X revisions back).

**Comment by strutt** [comment]
Yeah that sounds reasaonable enough. I just changed it.
